In [1]:
word=input("enter any word")
d={}
vowels={'a','e','i','o','u'}
for x in word:
    if x in vowels: 
        d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occure",v,"times")

enter any wordroshhii
o occure 1 times
i occure 2 times


In [3]:
n=[1,2,3,4,5,5,5,5]
print(n.count(5))

4


In [4]:
n=[1,2,3,4,5]
n.insert(1,888)
print(n)

[1, 888, 2, 3, 4, 5]


In [9]:
n=[1,2,3,4,5]
x=n.pop(1)
print(n)
print(x)

[1, 3, 4, 5]
2


In [11]:
n=[1,2,3,4,5]
for i in range(len(n)):
    print(i)

0
1
2
3
4


In [12]:
n=[1,2,3,4,5]
n.pop()
print(n)

[1, 2, 3, 4]


In [13]:
n=[1,2,3,4,5]
n.reverse()
print(n)

[5, 4, 3, 2, 1]


In [14]:
n=[1,2,3,4,5]
x=n[::-1]
print(x)

[5, 4, 3, 2, 1]


In [15]:
n=['rosh','ami','shi','sne']
n.sort()
print(n)

['ami', 'rosh', 'shi', 'sne']


In [16]:
n=[89,98,34,56]
n.sort()
print(n)

[34, 56, 89, 98]


In [17]:
n=['rosh',89,'ami',90,'shi','sne']
n.sort()
print(n)

TypeError: '<' not supported between instances of 'int' and 'str'

In [18]:
n=['rosh','ami','shi','sne']
n.sort(reverse=True)
print(n)

['sne', 'shi', 'rosh', 'ami']


In [20]:
x=[10,20,30,40]
y=x
y[1]=777
print(x)
print(y)


[10, 777, 30, 40]
[10, 777, 30, 40]


In [23]:
a=[10,20,30]
b=[40,50,60]
print(a+b)

[10, 20, 30, 40, 50, 60]


In [24]:
x=["MITE","MANGALORE","NITTE"]
y=["MITE","MANGALORE","NITTE"]
x==y
x!=y
z=["MITE","MANGALORE","NITTE"]
x==z

True

In [25]:
x=["MITE","MANGALORE","NITTE"]
y=["MITE","MANGALORE","NITTE"]
x==y


True

In [29]:
m=[10,20,30,40,[50,60,70]]
m[3]
m[4][1]


60

In [41]:
seq=[1,2,3,4,5]
def times2(seq):
    return seq*2
lambda avr:seq*2
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [46]:
seq=[1,2,3,4,5]
lambda var:var*2
list(map(lambda var: var*2,seq))
list(filter(lambda item:item%2==0,seq))
    

[2, 4]

In [50]:
import numpy as np
my_list=[1,2,3]
my_list
np.array(my_list)

array([1, 2, 3])

In [51]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [54]:
np.zeros(3)

array([0., 0., 0.])

In [56]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [60]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [66]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
np.random.randn(5,5)

array([[-0.65466606,  0.48776023,  0.16550531,  0.41900253, -1.73192754],
       [ 0.67038943,  0.08658556, -0.92334022,  0.32866134,  0.91233673],
       [-0.96816702, -2.38543149, -1.38513078, -0.64061132,  0.48324533],
       [-0.86598545,  1.12169478,  0.56589401,  1.06943047,  0.38879761],
       [-1.0128641 , -0.36813074,  0.70081815, -1.01426949, -0.70412634]])

In [70]:
x=np.random.randint(1,100,10)
print(x)

[ 2  5 49 56 11 63 40 87 81 25]


In [80]:
arr=np.arange(25)
runarr=np.random.randint(0,50,10)
arr.reshape(5,5)
arr.reshape(1,25)
runarr.max()
runarr.argmax()
arr.reshape(25,1).shape

(25, 1)

In [93]:
arr=np.arange(0,10)
#arr+arr
#arr*arr

#arr-arr
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [94]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [95]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [104]:
arr=np.arange(0,11)
arr
arr[8]
arr[1:5]
arr[0:5]
arr[0:5]=100
arr>4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [98]:
arr[8]

8

In [112]:
arr=np.zeros(12)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [120]:
arr=np.ones(15)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [121]:
arr[0:10]=5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 1. 1. 1. 1. 1.]


In [1]:
print("hello")

hello


In [2]:
import numpy as np
 pd
import pandas as

In [9]:
labels=['a','b','c']
my_array=[10,20,30]

In [10]:
pd.Series(data=my_array,index=labels)

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(my_array,labels)

a    10
b    20
c    30
dtype: int64

In [13]:
d={'a':10,'b':20,'c':30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [14]:
pd.Series([sum,len,print])

0      <built-in function sum>
1      <built-in function len>
2    <built-in function print>
dtype: object

In [16]:
data=[1,2,3,4]
index=['usa','russia','ucraine','england']
pd.Series(data,index)

usa        1
russia     2
ucraine    3
england    4
dtype: int64

In [22]:
print("hello")

hello


In [19]:
print("hello")

hello


In [21]:
index[2]='japan'
pd.Series(data,index)

usa        1
russia     2
japan      3
england    4
dtype: int64